/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package casim;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.assertNotNull;

/**
 * Example test class.
 */
class AppTest {
    /**
     * Example test.
     */
    @Test
    void appHasAGreeting() {
        final App classUnderTest = new App();
        assertNotNull("app should have a greeting", classUnderTest.getGreeting());
    }
}
