/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package casim;

import java.awt.GraphicsEnvironment;

import casim.ui.components.page.PageContainer;
import casim.utils.AppManager;
import javafx.application.Application;
import javafx.scene.Scene;
import javafx.stage.Stage;

/**
 * Main project class.
 */
public class App extends Application {
    private PageContainer root;

    /**
     * Entry point.
     * 
     * @param args command line args.
     */
    public static void main(final String[] args) {
        launch(args);
    }

    @Override
    public void start(final Stage primaryStage) throws Exception {
        final var graphics = GraphicsEnvironment.getLocalGraphicsEnvironment().getDefaultScreenDevice();
        final var width = graphics.getDisplayMode().getWidth() / 2;
        final var height = graphics.getDisplayMode().getHeight() / 2;

        primaryStage.setWidth(width);
        primaryStage.setHeight(height);

        root = new PageContainer(primaryStage);
        AppManager.showMainMenu(root);
        final var scene = new Scene(root);
        primaryStage.setScene(scene);
        primaryStage.show();
    }

    @Override
    public void stop() throws Exception {
        root.close();
    }
}
